commitish: main

name-template: "Release ${{ version }}"
tag-template: "$MAJOR.$MINOR.$PATCH"
change-template: "- [#{{number}}]({{url}}) {{title}}"
no-changes-template: "No changes in this release."

categories:
  - title: "🚀 Features"
    labels:
      - feature
  - title: "🐛 Bug Fixes"
    labels:
      - bug
  - title: "🧰 Maintenance"
    labels:
      - chore

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/${{ repository.owner.login }}/{{ repository.name }}/compare/${{ previousTag }}...${{ currentTag }}
