commitish: main

name-template: "Release {{version}}"
tag-template: "v{{version}}"
change-template: "- [#{{number}}]({{url}}) {{title}}"
no-changes-template: "No changes in this release."

categories:
  - title: "🚀 Features"
    labels:
      - feature
  - title: "🐛 Bug Fixes"
    labels:
      - bug
  - title: "🧰 Maintenance"
    labels:
      - chore

template: |
  ## What's Changed

  {{changes}}

  **Full Changelog**: https://github.com/{{owner}}/{{repo}}/compare/{{previousTag}}...{{currentTag}}
