name: Build Stealerium

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout ✨
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      # Add MSBuild to the PATH
      - name: Add msbuild to PATH 🔗
        uses: microsoft/setup-msbuild@v1.1

      # Install dependencies
      - name: Restore NuGet Packages 📦
        run: nuget restore Stealerium.sln

      # Build solution
      - name: Build solution for release 🧱
        run: msbuild -nologo -v:m -p:Configuration=Release Stealerium.sln

      # Extract version from Stub/Config.cs
      - name: Extract version from Config.cs
        id: extract_version
        shell: pwsh
        run: |
          $version = Select-String -Path "Stub/Config.cs" -Pattern 'Version = "([0-9.]+)"' | ForEach-Object {
            $_.Matches.Groups[1].Value
          }
          echo "Version extracted: $version"
          echo "::set-output name=release_version::$version"

      # Create Git tag and push to the repository
      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.extract_version.outputs.release_version }}
          git push origin ${{ steps.extract_version.outputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build Artifact
      - name: Archive Stealerium 🧱
        uses: thedoctor0/zip-release@master
        with:
          path: ${{ github.workspace }}\Binaries\Release\net8.0-windows\.
          type: "zip"
          filename: "Stealerium.zip"

      # Draft Release Notes
      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          version: ${{ steps.extract_version.outputs.release_version }}
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload Release Asset
      - name: Upload Release Asset 📦
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.release_version }}
          files: Stealerium.zip
          generate_release_notes: true
